"""Add lecturer_timeslot association table

Revision ID: addbe64c25e2
Revises: 2793b8c4d8be
Create Date: 2025-06-16 00:39:35.833262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addbe64c25e2'
down_revision: Union[str, None] = '2793b8c4d8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer_timeslot',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('lecturer_id', 'timeslot_id')
    )
    op.drop_column('lecturers', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('availability', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('lecturer_timeslot')
    # ### end Alembic commands ###
